CONTRIBUTING.md

A simple outline documenting how developement happens in this repository

Contribution guidelines for branch management

---

.smalltalk.ston
CI/RequireFFI.st

Setup .ston files and required items for FFI import

---

packages/TelegramClient-Core.package/TeleClient.class/class/CreateClient.st
packages/TelegramClient-Core.package/TeleClient.class/class/DeleteClient..st
packages/TelegramClient-Core.package/TeleClient.class/methodProperties.json
packages/TelegramClient-Tests.package/TeleClientTests.class/instance/initialize.st
packages/TelegramClient-Tests.package/TeleClientTests.class/instance/testDestroyClearsHandle.st
packages/TelegramClient-Tests.package/TeleClientTests.class/methodProperties.json
packages/TelegramClient-Tests.package/TeleClientTests.class/properties.json

Fixed Tests, removed unused code

Fixed tests, removed unused methods

---

README.md

Added status badges to readme.md

Update README.md to include status badges

---

README.md

Fixed linux installation instructions (issue #94)

---

.github/ci.yml
.github/workflows/main.yml

I removed the trunk again, this time also in main.yml.

removed trunk also in main.yml

---

README.md

Added running command to Readme
closes #146

Added running command

---

packages/TelegramClient-Core.package/TCCAbstractTeleClientFactory.class/instance/client..st
packages/TelegramClient-Core.package/TCCAbstractTeleClientFactory.class/instance/client.st

made tests on develop green again.
closes #159

removed Linter Problems

---

packages/TelegramClient-UI.package/TCUChatMessageList.class/instance/addMessage..st
packages/TelegramClient-UI.package/TCUChatMessageList.class/instance/defaultMessageMargin.st
packages/TelegramClient-UI.package/TCUChatMessageList.class/methodProperties.json
packages/TelegramClient-UI.package/TCUMessage.class/instance/initialize.st
packages/TelegramClient-UI.package/TCUMessage.class/methodProperties.json

Customer wanted Messages in single Color. Now also with rounded corners :)
closes #158

Messages only using Single Color

---

packages/TelegramClient-UI.package/TCUDefaultValues.class/class/colorLightRed.st
packages/TelegramClient-UI.package/TCUDefaultValues.class/class/colorRed.st
packages/TelegramClient-UI.package/TCUDefaultValues.class/methodProperties.json
packages/TelegramClient-UI.package/TCUMain.class/instance/addCloseButtonTo.withSpacing..st
packages/TelegramClient-UI.package/TCUMain.class/instance/addHeader.st
packages/TelegramClient-UI.package/TCUMain.class/methodProperties.json

closes #95 
Added a close button to the UI without logging of.

Added a close button to the UI

---

.smalltalk.ston

Added a default Timeout to CI

---

README.md

all libraries belong in the resource folder, closes #203

Update README.md to reference correct ffi directory for libraries

---

packages/TelegramClient-UI.package/TCUMessage.class/instance/setText..st
packages/TelegramClient-UI.package/TCUMessage.class/methodProperties.json

Lock message text

---

packages/TelegramClient-Core.package/TCCCore.class/instance/handleEvent..st
packages/TelegramClient-Core.package/TCCCore.class/instance/tryHandleError..st
packages/TelegramClient-Core.package/TCCCore.class/methodProperties.json
packages/TelegramClient-Core.package/TCCErrorConstants.class/README.md
packages/TelegramClient-Core.package/TCCErrorConstants.class/class/UnknownUsername.st
packages/TelegramClient-Core.package/TCCErrorConstants.class/class/unknownUsername.st
packages/TelegramClient-Core.package/TCCErrorConstants.class/methodProperties.json
packages/TelegramClient-Core.package/TCCErrorConstants.class/properties.json

Added error handler for wrong username messages

---

packages/TelegramClient-Core.package/TCCCore.class/instance/tryHandleError..st
packages/TelegramClient-Core.package/TCCCore.class/methodProperties.json
packages/TelegramClient-Core.package/TCCErrorConstants.class/class/tdlibAlreadyInUse.st
packages/TelegramClient-Core.package/TCCErrorConstants.class/methodProperties.json

Added error messages for tdlib already in used

---

packages/TelegramClient-Core.package/TCCCore.class/instance/tryHandleError..st
packages/TelegramClient-Core.package/TCCCore.class/methodProperties.json
packages/TelegramClient-Core.package/TCCErrorConstants.class/class/invalidAuthenticationCode.st
packages/TelegramClient-Core.package/TCCErrorConstants.class/class/invalidPhoneNumber.st
packages/TelegramClient-Core.package/TCCErrorConstants.class/methodProperties.json

Handle errors occuring at login

---

packages/TelegramClient-Core.package/TCCFFIClient.class/instance/setLogLevel..st
packages/TelegramClient-Core.package/TCCFFIClient.class/methodProperties.json
packages/TelegramClient-Core.package/TCCTeleClientFactory.class/instance/createClient..st
packages/TelegramClient-Core.package/TCCTeleClientFactory.class/methodProperties.json

Set log level after client creation

---

packages/TelegramClient-Core.package/TCCCore.class/instance/authSucceeded.st
packages/TelegramClient-Core.package/TCCCore.class/instance/getOwnProfile.st
packages/TelegramClient-Core.package/TCCCore.class/instance/handleEvent..st
packages/TelegramClient-Core.package/TCCCore.class/instance/setUserID..st
packages/TelegramClient-Core.package/TCCCore.class/methodProperties.json

Correctly identify own user id

---

.github/workflows/main.yml

closes #243 
This PR will reduce the used squeak versions to one (squeak 5.2).  This should fix the issue described in #243 .

CI will only execute on one branch

---

.github/workflows/ci-linter.yml
.github/workflows/main.yml

CI will be executed on every branch and not only on master and dev.
We should discuss this:
Advantages:
Everyone can immediately see which tests/lintingtests are failing and could fix this. He is not forced to pull it in squeak and then to run the tests
Disadvantages:
I do not know any so far. To my mind it is not bad to run the CI more frequently

Released CI limits to master/dev

---

.github/workflows/ci-linter.yml
.github/workflows/main.yml

reverted released limits of the CI to develop and master
closes #277

Revert #277

---

packages/TelegramClient-Tests.package/TCTSarFileGenerator.class/instance/generatePreamble.uipackage.nativeResourceFolder..st
packages/TelegramClient-Tests.package/TCTSarFileGenerator.class/methodProperties.json

Fixed missing dlls on windows

---

packages/TelegramClient-Core.package/TCCFFIClient.class/class/newForCurrentOS.st
packages/TelegramClient-Core.package/TCCFFIClient.class/methodProperties.json
packages/TelegramClient-Core.package/TCCTeleClient.class/class/newForCurrentOS.st
packages/TelegramClient-Core.package/TCCTeleClient.class/class/newWithClient..st
packages/TelegramClient-Core.package/TCCTeleClient.class/methodProperties.json
packages/TelegramClient-Tests.package/TCTSarFileGenerator.class/instance/generatePreamble.uipackage.nativeResourceFolder..st
packages/TelegramClient-Tests.package/TCTSarFileGenerator.class/instance/testCreateSarFile.st
packages/TelegramClient-Tests.package/TCTSarFileGenerator.class/methodProperties.json

added autodownload in sar file

---

packages/TelegramClient-Core.package/TCCWindowsClient.class/class/downloadArchive.st
packages/TelegramClient-Core.package/TCCWindowsClient.class/methodProperties.json

Fix MNU when installing latest release on Windows

---

packages/TelegramClientTests-Core.package/TCTCCoreResource.class/instance/isCoreReadyForSetup.st
packages/TelegramClientTests-Core.package/TCTCCoreResource.class/instance/setUp.st
packages/TelegramClientTests-Core.package/TCTCCoreResource.class/methodProperties.json
packages/TelegramClientTests-Core.package/TCTCTestCore.class/instance/loginWithTestData.st
packages/TelegramClientTests-Core.package/TCTCTestCore.class/methodProperties.json

Replaces fixed waiting times with dynamic waiting for a specific condition, to eliminate race conditions which freeze the pipeline in an infinite wait.

Fix pipeline race condition

---

.github/workflows/main.yml
packages/TelegramClient-Core.package/TCCGroupChat.class/instance/initializeFromChatEvent..st
packages/TelegramClient-Core.package/TCCGroupChat.class/methodProperties.json
packages/TelegramClient-UI.package/TCUEmojiHelper.class/class/textFor..st
packages/TelegramClient-UI.package/TCUEmojiHelper.class/methodProperties.json
packages/TelegramClient-UI.package/TCUPhotoMessage.class/instance/addPhoto.st
packages/TelegramClient-UI.package/TCUPhotoMessage.class/methodProperties.json
packages/TelegramClientTests-UI.package/TCTUTestCase.class/instance/expectedFailures.st
packages/TelegramClientTests-UI.package/TCTUTestCase.class/instance/expectedSqueak5_2Failures.st
packages/TelegramClientTests-UI.package/TCTUTestCase.class/methodProperties.json

Drop support for Squeak 5.2

---

packages/TelegramClient-Core.package/TCCLinuxClient.class/class/downloadUrl.st
packages/TelegramClient-Core.package/TCCLinuxClient.class/methodProperties.json
packages/TelegramClient-Core.package/TCCMacClient.class/class/downloadUrl.st
packages/TelegramClient-Core.package/TCCMacClient.class/methodProperties.json
packages/TelegramClient-Core.package/TCCWindowsClient.class/class/downloadUrl.st
packages/TelegramClient-Core.package/TCCWindowsClient.class/methodProperties.json

Update tdlib links

---

packages/TelegramClient-Core.package/TCCWindowsClient.class/class/downloadArchive.st
packages/TelegramClient-Core.package/TCCWindowsClient.class/class/moduleName.st
packages/TelegramClient-Core.package/TCCWindowsClient.class/methodProperties.json

Reverts hpi-swa-teaching/TelegramClient#454

Revert "do not attempt to unpack DLL"

---

packages/TelegramClient-Core.package/TCCChats.class/class/defaultSortBlock.st
packages/TelegramClient-Core.package/TCCChats.class/methodProperties.json
packages/TelegramClient-UI.package/TCUChatsList.class/instance/redrawItems.st
packages/TelegramClient-UI.package/TCUChatsList.class/methodProperties.json
packages/TelegramClientTests-Core.package/TCTCChatsTests.class/instance/testPositionInsert.st
packages/TelegramClientTests-Core.package/TCTCChatsTests.class/instance/testPositionModify.st
packages/TelegramClientTests-Core.package/TCTCChatsTests.class/instance/testSortingUnknownPositions.st
packages/TelegramClientTests-Core.package/TCTCChatsTests.class/methodProperties.json
packages/TelegramClientTests-UI.package/TCTUChatsListTests.class/README.md
packages/TelegramClientTests-UI.package/TCTUChatsListTests.class/instance/testChatOrderUpdatesIfPositionChanges.st
packages/TelegramClientTests-UI.package/TCTUChatsListTests.class/instance/testChatTitleVisible.st
packages/TelegramClientTests-UI.package/TCTUChatsListTests.class/instance/testLastMessageVisible.st
packages/TelegramClientTests-UI.package/TCTUChatsListTests.class/methodProperties.json
packages/TelegramClientTests-UI.package/TCTUChatsListTests.class/properties.json

Refactor Add tests

---

packages/TelegramClient-UI.package/TCUMessage.class/class/defaultTextMorph.st
packages/TelegramClient-UI.package/TCUMessage.class/methodProperties.json

- Messages are now readOnly instead of locked. 
closes #481

Make messages copyable
